export enum ReportEventType {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  PAYMENT_CAPTURED = 'PAYMENT_CAPTURED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  INVENTORY_DEDUCTED = 'INVENTORY_DEDUCTED',
  INVENTORY_RESTORED = 'INVENTORY_RESTORED',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  PROMOTION_APPLIED = 'PROMOTION_APPLIED',
}
