export const SystemRoleNames = {
  OWNER: 'owner',
  ADMIN: 'admin',
  MANAGER: 'manager',
  STAFF: 'staff',
  DRIVER: 'driver',
  FULFILLMENT: 'fulfillment',
  CUSTOMER: 'customer',
} as const;

/** Roles created automatically for new tenants during signup. */
export const DEFAULT_TENANT_ROLE_NAMES = [
  SystemRoleNames.OWNER,
  SystemRoleNames.MANAGER,
  SystemRoleNames.STAFF,
  SystemRoleNames.DRIVER,
  SystemRoleNames.FULFILLMENT,
] as const;

export const OnboardingPermissionKeys = {
  TENANT_SETTINGS_READ: 'tenant:settings:read',
  TENANT_SETTINGS_UPDATE: 'tenant:settings:update',
  TENANT_BRANDING_UPDATE: 'tenant:branding:update',
  TENANT_BILLING_READ: 'tenant:billing:read',
  TENANT_BILLING_UPDATE: 'tenant:billing:update',
  ONBOARDING_READ: 'onboarding:read',
  ONBOARDING_UPDATE: 'onboarding:update',
  STAFF_READ: 'staff:read',
  STAFF_INVITE: 'staff:invite',
  STAFF_UPDATE: 'staff:update',
} as const;

const CATALOG = [
  'catalog.read',
  'catalog.write',
  'inventory.read',
  'inventory.write',
  'orders.read',
  'orders.write',
  'fulfillment.read',
  'fulfillment.write',
  'staff.read',
  'staff.write',
  'locations.read',
  'locations.write',
  'billing.read',
  'billing.write',
  'analytics.read',
  'audit.read',
  'integrations:read',
  'integrations:create',
  'integrations:update',
  'integrations:delete',
  'integration-events:read',
  'integration-logs:read',
  'api-keys:read',
  'api-keys:create',
  'api-keys:delete',
  'notifications:read',
  'notifications:create',
  'notification-logs:read',
  'notification-templates:read',
  'notification-templates:create',
  'notification-templates:update',
  'notification-channels:read',
  'notification-channels:create',
  'notification-channels:update',
  'notification-channels:delete',
  'tenants:read',
  'tenants:create',
  'tenants:update',
  'tenants:delete',
  'users:read',
  'users:create',
  'users:update',
  'users:delete',
  'roles:read',
  'roles:create',
  'roles:assign',
  'roles:update',
  'roles:delete',
  'permissions:read',
  'products:read',
  'products:create',
  'products:update',
  'products:delete',
  'categories:read',
  'categories:create',
  'categories:update',
  'orders:read',
  'orders:update',
  'inventory:read',
  'inventory:update',
  'pos:access',
  'pos:cart',
  'pos:checkout',
  'pos:payment',
  'pos:receipt',
  'pos:catalog',
  'orders:create',
  'orders:cancel',
  'kds:access',
  'kds:read',
  'kds:update',
  'deliveries:read',
  'deliveries:update',
  'reports:read',
  ...Object.values(OnboardingPermissionKeys),
  'admin:access',
  'admin:products',
  'admin:inventory',
  'admin:orders',
  'admin:promotions',
  'admin:reports',
  'admin:settings',
  'locations:read',
  'locations:create',
  'locations:update',
  'locations:delete',
];

export const ALL_PERMISSION_KEYS = [...new Set(CATALOG)];

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  [SystemRoleNames.OWNER]: ['*'],
  [SystemRoleNames.ADMIN]: ['*'],
  [SystemRoleNames.MANAGER]: [
    'catalog.read',
    'catalog.write',
    'inventory.read',
    'inventory.write',
    'orders.read',
    'orders.write',
    'fulfillment.read',
    'fulfillment.write',
    'staff.read',
    'staff.write',
    'locations.read',
    'locations.write',
    'analytics.read',
    'integrations:read',
    'integrations:create',
    'integrations:update',
    'integration-events:read',
    'integration-logs:read',
    'api-keys:read',
    'api-keys:create',
    'api-keys:delete',
    'admin:access',
    'admin:products',
    'admin:inventory',
    'admin:orders',
    'admin:reports',
    'permissions:read',
    'notifications:read',
    'notifications:create',
    'notification-logs:read',
    'notification-templates:read',
    'notification-templates:create',
    'notification-templates:update',
    'notification-channels:read',
    'notification-channels:create',
    'notification-channels:update',
    'notification-channels:delete',
    'products:read',
    'products:create',
    'products:update',
    'products:delete',
    'categories:read',
    'categories:create',
    'categories:update',
    'orders:read',
    'orders:update',
    'inventory:read',
    'inventory:update',
    'reports:read',
    'pos:cart',
    'pos:checkout',
    'pos:payment',
    'pos:receipt',
    'pos:catalog',
    'orders:read',
    'orders:create',
    'kds:read',
    'kds:update',
    OnboardingPermissionKeys.ONBOARDING_READ,
    OnboardingPermissionKeys.STAFF_READ,
    OnboardingPermissionKeys.STAFF_UPDATE,
  ],
  [SystemRoleNames.STAFF]: [
    'orders.read',
    'orders.write',
    'fulfillment.read',
    'fulfillment.write',
    'pos:access',
    'pos:cart',
    'pos:checkout',
    'pos:payment',
    'pos:receipt',
    'pos:catalog',
    'kds:access',
    'kds:read',
    'kds:update',
    'orders:read',
    'orders:create',
  ],
  [SystemRoleNames.DRIVER]: ['deliveries:read', 'deliveries:update'],
  [SystemRoleNames.FULFILLMENT]: [
    'fulfillment.read',
    'fulfillment.write',
    'kds:access',
    'kds:read',
    'kds:update',
    'orders:read',
  ],
  [SystemRoleNames.CUSTOMER]: [],
};

export function resolveRolePermissions(roleName: string, assigned: string[]): string[] {
  if (assigned.length > 0) {
    return assigned;
  }
  return ROLE_PERMISSION_MAP[roleName] ?? [];
}

export function permissionAllowed(userPermissions: string[], required: string): boolean {
  if (userPermissions.includes('*')) {
    return true;
  }
  if (userPermissions.includes(required)) {
    return true;
  }
  const aliases = PERMISSION_ALIASES[required] ?? [];
  if (aliases.some((alias) => userPermissions.includes(alias))) {
    return true;
  }
  if (
    userPermissions.includes('kds:access') &&
    (required === 'kds:read' || required === 'kds:update')
  ) {
    return true;
  }
  return false;
}

const PERMISSION_ALIASES: Record<string, string[]> = {
  'products:read': ['catalog.read'],
  'products:create': ['catalog.write'],
  'products:update': ['catalog.write'],
  'products:delete': ['catalog.write'],
  'categories:read': ['catalog.read'],
  'categories:create': ['catalog.write'],
  'categories:update': ['catalog.write'],
  'inventory:read': ['inventory.read'],
  'inventory:update': ['inventory.write'],
  'admin:inventory': ['inventory.read', 'inventory.write'],
  'orders:read': ['orders.read'],
  'orders:create': ['orders.write'],
  'orders:update': ['orders.write'],
  'orders:cancel': ['orders.write'],
  'kds:access': ['fulfillment.read'],
  'kds:read': ['fulfillment.read'],
  'kds:update': ['fulfillment.write'],
  'locations:read': ['locations.read'],
  'locations:create': ['locations.write'],
  'locations:update': ['locations.write'],
  'locations:delete': ['locations.write'],
  'admin:reports': ['analytics.read'],
  'reports:read': ['analytics.read'],
  'tenant:billing:read': ['billing.read'],
  'tenant:billing:update': ['billing.write'],
  'users:read': ['staff.read'],
  'users:create': ['staff.write'],
  'users:update': ['staff.write'],
  'users:delete': ['staff.write'],
  'roles:read': ['staff.read'],
  'roles:create': ['staff.write'],
  'roles:update': ['staff.write'],
  'roles:delete': ['staff.write'],
  'roles:assign': ['staff.write'],
};
