export const AdminPermissionKeys = {
  ACCESS: 'admin:access',
  PRODUCTS: 'admin:products',
  INVENTORY: 'admin:inventory',
  ORDERS: 'admin:orders',
  PROMOTIONS: 'admin:promotions',
  REPORTS: 'admin:reports',
  SETTINGS: 'admin:settings',
  FRANCHISE_HQ: 'admin:franchise-hq',
  AUDIT_READ: 'audit.read',
  CRM_READ: 'crm.read',
  CRM_WRITE: 'crm.write',
  SUBSCRIPTIONS_READ: 'subscriptions.read',
  SUBSCRIPTIONS_WRITE: 'subscriptions.write',
  MARKETING_READ: 'marketing.read',
  MARKETING_WRITE: 'marketing.write',
} as const;
