export const CatalogPermissionKeys = {
  CATEGORIES_READ: 'categories:read',
  CATEGORIES_CREATE: 'categories:create',
  CATEGORIES_UPDATE: 'categories:update',
  CATEGORIES_DELETE: 'categories:delete',
  PRODUCTS_READ: 'products:read',
  PRODUCTS_CREATE: 'products:create',
  PRODUCTS_UPDATE: 'products:update',
  PRODUCTS_DELETE: 'products:delete',
  VARIANTS_READ: 'variants:read',
  VARIANTS_CREATE: 'variants:create',
  VARIANTS_UPDATE: 'variants:update',
  VARIANTS_DELETE: 'variants:delete',
  MODIFIERS_READ: 'modifiers:read',
  MODIFIERS_CREATE: 'modifiers:create',
  MODIFIERS_UPDATE: 'modifiers:update',
  MODIFIERS_DELETE: 'modifiers:delete',
  ADDONS_READ: 'addons:read',
  ADDONS_CREATE: 'addons:create',
  ADDONS_UPDATE: 'addons:update',
  ADDONS_DELETE: 'addons:delete',
} as const;
